def gen():
    try:
        yield "ok"
    except GeneratorExit:
        print "caught"
    yield "failure at runtime!"

def test():
    x = gen()
    print x
    print x.close()
